name: dockerchallenge

services:
  
  app:
    image: nginx
    networks:
      custom_bridge:
        aliases:
          - frontend

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    
networks:
  custom_bridge:
    driver: bridge